---
# tasks file for nokeval_reader
- name: Install required packages
  apt:
    name: "{{ nokeval_reader_required_packages }}"
    state: "{{ nokeval_reader_package_state }}"

- name: Add nokeval_reader repo
  template:
    src: measurinator.list.j2
    dest: /etc/apt/sources.list.d/measurinator.list
  register: nokeval_reader_repo

- name: Install nokeval_reader package
  apt:
    name: "{{ nokeval_reader_package }}"
    state: "{{ nokeval_reader_package_state }}"
    update_cache: true
  notify: restart nokeval_reader service

- name: Create configuration file
  template:
    src: config.yaml.j2
    dest: /opt/nokeval_reader/config.yaml
    owner: reader
    group: reader
  notify: restart nokeval_reader service

- name: Start and enable nokeval_reader service
  systemd:
    name: nokeval_reader.service
    enabled: yes
    state: started
